config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy, :show]
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
   }

  resources :users, only: %i[show index]

  root 'topics#index'
  resources :topics do
    resources :comments
  end

  resources :favorites, only: [:create, :destroy, :index]

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user 
    belongs_to :topic
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
       favorite = current_user.favorites.create(topic_id: params[:topic_id])
       flash[:success] = "Vous avez ajouté #{favorite.topic.title} à vos sujets favorit"
       redirect_to topic_path(favorite.topic.id)
   end

   def destroy
       favorite = current_user.favorites.find_by(id: params[:id]).destroy
       flash[:success] = "#{favorite.topic.title} n'est plus dans vos favorites"
       redirect_to topic_path(favorite.topic.id), notice: "The #{favorite.topic.user.name}'s  post is removed from your favorites"
   end

   def index
       @favorite = current_user.favorites.all
       @topic=Topic.all
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<%@favorite.each do |favorite|%>
    <p>
      <strong>Subject </strong> : <%=link_to "#{@topic.find(favorite.topic_id).title}", topic_path(favorite.topic_id)  %> <br>
        posted by <strong><%= @topic.find(favorite.topic_id).user.name %></strong> at <strong><%= @topic.find(favorite.topic_id).created_at %></strong>
    </p>
    <p>
      <%= @topic.find(favorite.topic_id).content %>
    </p>
    <p>
      comments : <span class="badge badge-info"><%= @topic.find(favorite.topic_id).comments.count %></span>
      like : <span class="badge badge-danger"><%= @topic.find(favorite.topic_id).favorites.count %></span>
    </p>
    <hr>
<% end %>

app/views/favorites/show.html.erb
<% if logged_in?%>
<div class="container">
  <div class="row">  
      <div class="col-12">
        <div class="container insta-post">
          <table class="table" style="overflow:hidden;"> 
          <%if @favorite.present?%>
            <% @favorite.each do |favorite|%>
              <thead class="thead-dark">
                <tr>
                  <th>User Name</th>
                  <th>Image</th>  
                  <th>Content</th>  
                  <%# <th>Action</th> %>
                </tr> 
              </thead>
              <tbody>
              <tr>
                <td>
                  <%= favorite.topic.user.name %>
                </td> 
                <td>
                  <%= image_tag favorite.topic.image_url, class: "profile-pic" %>
                </td>
                <td>
                  <%= favorite.topic.content %>
                </td>
                <td>
                  <div class="col-6">
                    <% if @favorite.present? %>
                      <%= link_to 'Delete Favorite', favorite_path(id: @favorite.ids), method: :delete, class: 'btn btn-danger' %>
                    <% else %>
                      <%= link_to 'Add Favorite', favorites_path(topic_id: @topic.id), method: :post, class: 'btn btn-secondary' %>
                    <% end %>
                  </div>
                </td>
              </tr>
              </tbody> 
            <% end %>
          <%else%>
            <p>You aren't added favorite  go to post page and add.</p>
          <%= link_to  "See The Post List", topics_path, class: "btn btn-primary" %>
          <%end%>   
          </table>
        </div> 
      </div>
<%else%>
  <div class="row">
    <div class="col-6">
      Please Sign In :<span class="badge badge-pill badge-info">
        <%= link_to  "Log in", new_session_path %></span>
    </div>
    <div class="col-6">
      Please Sign Up :<span class="badge badge-pill badge-info">
        <%= link_to  "Sign Up", new_user_path %></span>
    </div>
  </div>
<%end%>
        </div>
      </div>
  </div>
</div>