config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy, :show]
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
   }

  resources :users, only: %i[show index]

  root 'topics#index'
  resources :topics do
    resources :comments
  end

  resources :favorites, only: [:create, :destroy, :index]

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :topic
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, only: %i[create edit update destroy]
    before_action :set_topic, only: %i[create edit update destroy]

    def create
      @comment = @topic.comments.build(comment_params)
      @comment.user_id = current_user.id
      respond_to do |format|
        if @topic.save
          format.js { render :index }
        else
          format.html { redirect_to topic_path(@topic), notice: I18n.t('comment.not_save') }
        end
      end
    end

    def edit
        @comment = @topic.comments.find(params[:id])
        respond_to do |format|
          format.js { render :edit }
        end
      end

      def update
        @comment = @topic.comments.find(params[:id])
        respond_to do |format|
          if @comment.update(comment_params)
            flash.now[:notice] = I18n.t('comment.update')
            format.js { render :index }
          else
            flash.now[:notice] = I18n.t('comment.not_update')
            format.js { render :edit_error }
          end
        end
      end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      respond_to do |format|
        flash.now[:notice] = I18n.t('comment.destroy')
        format.js { render :index }
      end
   end

    private

    def comment_params
      params.require(:comment).permit(:topic_id, :comment)
    end

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def login_check
      unless user_signed_in?
        redirect_to new_user_session_path, notice: I18n.t('comment.login_check')
      end
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [topic, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %>undefined</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :comment, id: "comment_comment_#{@topic}",class:"form-control" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [topic, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %>undefined</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-10">
      <%= form.text_area :comment,:class=>"comment form-control", placeholder:'Give your opinion on this topic here '%>
    </div>
      <div class="col-sm-2">
        <%= form.submit 'comment',:class=>"btn btn-outline-info my-2 my-sm-0" %>
      </div>
    </div>
<% end %>

app/views/comments/_index.html.erb
  <% comments.each do |comment| %>
      <% if comment.id.present? %>
      <div class="comment-comment" id ="this_comment_<%= comment.id %>"></div>
      <div class="card">
        <div class="card-header">
             <strong><%= image_tag (comment.user.avatar_thumbnail), class:"navbar-brand" , style:'height:50px;width:50px;border-radius:100px;'%>
                    <%= link_to "#{comment.user.name }", user_path(comment.user.id) %></strong> comment<br>
        </div>
        <div class="card-body">
        <p><%= comment.comment %></p>
          <% if user_signed_in? %>
             <% if comment.user_id == current_user.id %>
              <small><%= link_to "edit comment", edit_topic_comment_path(@topic, comment), remote: true %></small>
              | <small><%= link_to "delete comment", topic_comment_path(comment.topic_id, comment.id), method: :delete, remote: true %></small>
             <% end %>

          <% end %>
      </div>
      </div>
        <% end %>
      <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', topic: @topic, comment: @comment %>");

app/views/comments/index.js.erb
$('#comments_area').html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$("textarea").val('')