config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy, :show]
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
   }

  resources :users, only: %i[show index]

  root 'topics#index'
  resources :topics do
    resources :comments
  end

  resources :favorites, only: [:create, :destroy, :index]

end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :user
    validates :content, presence:true
    validates :title, presence:true
    validates :category, presence:true
    enum category: %i[Actualité Loisir Sport Mode Tourisme Politique Voyage Sexe Cuisine]
    # comment fonction
    has_many :comments, dependent: :destroy
    #favorites function
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
     # collbacks
    before_action :authenticate_user!, only: %i[new edit destroy]
    before_action :set_topic, only: [:show, :edit, :update, :destroy]
    before_action :user_check, only: %i[edit destroy]
    # has_many :favorite_users, through: :favorites, source: :user
    # belongs_to :user

    def index
        if params[:title]
          @topic= Topic.where(["title LIKE ?", "%#{params[:title]}%"])
       elsif params[:sort_my_topic]
         @topic= current_user.topic
       elsif params[:sort_actuality]
         @topic= Topic.where(["category=0"])
       elsif params[:sort_losir]
         @topic= Topic.where(["category=1"])
       elsif params[:sort_sport]
         @topic= Topic.where(["category=2"])
       elsif params[:sort_mode]
         @topic= Topic.where(["category=3"])
       elsif params[:sort_tourism]
         @topic= Topic.where(["category=4"])
       elsif params[:sort_politique]
         @topic= Topic.where(["category=5"])
       elsif params[:sort_voyage]
         @topic= Topic.where(["category=6"])
       elsif params[:sort_sexe]
         @topic= Topic.where(["category=7"])
       elsif params[:sort_cuisine]
         @topic= Topic.where(["category=8"])
       else
        @topic= Topic.all
      end
    end

    def new
      @topic = Topic.new
    end

    def create
        @topic = Topic.new(topic_params)
        # id user a l'enregistrement
        @topic.user_id = current_user.id
        if @topic.save
            flash[:success] = I18n.t('topic.create')
            redirect_to topics_path
        end
    end

    def edit

    end

    def show
      @favorite = @topic.favorites.find_by(topic_id: @topic.id)
      @comments = @topic.comments
      @comment = @topic.comments.build
    end

    def update
      if @topic.update(topic_params)
      flash[:success] =  I18n.t('topic.update')
      redirect_to topics_path
    else
      render :edit
    end
    end
    def destroy
      @topic.destroy
      flash[:success] = I18n.t('topic.destroy')
      redirect_to topics_path
    end
    private
    def topic_params
      params.require(:topic).permit(:title,:content,:category)
    end
    def set_topic
      @topic=Topic.find(params[:id])
    end
    def user_check
     unless current_user.id == @topic.user.id
      flash[:success] = I18n.t('topic.user_check')
     end
    end
    # vérifier que l'utilisateur connecté est le propriétaire

    # empêcher à l'utilisateur de publier ou éditer ou supprimer sans être connecter ou s'il n'est pas propiétaire vérifier que l'utilisateur est connecté

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_category_sort.html.erb
<div class="category_display">
  <strong>Sort by categories : </strong>
  <button type="button" class="btn-black">
    <%= link_to 'Actualité', topics_path(sort_actuality: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=0").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Loisir', topics_path(sort_losir: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=1").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Sport', topics_path(sort_sport: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=2").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Mode', topics_path(sort_mode: "true")%>
    <span class="badge badge-info"><%= @topic.where("category=3").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Tourisme', topics_path(sort_tourism: "true")%>
    <span class="badge badge-info"><%= @topic.where("category=4").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Politique', topics_path(sort_politique: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=5").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Voyage', topics_path(sort_voyage: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=6").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Sexe', topics_path(sort_sexe: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=7").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Cuisine', topics_path(sort_cuisine: "true") %>
    <span class="badge badge-info"><%= @topic.where("category=8").count%></span>
  </button>
</div>

app/views/topics/_footer.html.erb
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">DF_CONTACT</h4>
                        <p class="lead mb-0">
                            2215 Calavi DF Store
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">SOCIAL MEDIA</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">SOME SUBJECTS</h4>
                        <p class="lead mb-0">
                            <% Topic.all.limit(6).each do |topic|%>
                              <%= link_to "#{topic.title}", topic_path(topic.id)%>,
                            <% end%>
                          </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright © Africa Samurai | DIVER  2020</small></div>
        </div>

app/views/topics/_form.html.erb
<div class="container">
  <% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@topic.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= form_with(model:@topic,local: true) do |form| %>
    Choose one category
        <%= form.select(:category, {Actualité:"Actualité",
                                   Loisir:"Loisir",
                                   Sport:"Sport",
                                   Mode:"Mode",
                                   Tourisme:"Tourisme",
                                   Politique:"Politique",
                                   Voyage:"Voyage",
                                   Sexe:"Sexe",
                                   Cuisine:"Cuisine"})%><br>
    Topic title :
        <%= form.text_field :title,:class=>"form-control",:id=>"exampleInputEmail1" %><br>
    Topic Content :
        <%= form.text_area :content,:class=>"form-control",:id=>"topic_content" %><br>
  <div class="actions">
          <%= form.submit "Post",:class=>"btn btn-primary"%>
        </div>
    <% end %>
</div>
</div>

app/views/topics/confirm.html.erb
<div class="container">
<h3>Confirm your Topic</h3>
<%= form_with(model: @topic, url:topics_path,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= image_tag(@topic.image.url) if @topic.image && @topic.image.url%>
  <%= form.hidden_field :image_cache,:class=>"img-fluid rounded mx-auto d-block",
                                    :alt=>"Responsive image" %>
  <p>Content :<%= @topic.content %> </p>
  <%= form.submit "Confirm" %>
<% end %>
<%= form_with(model:@feed, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div

app/views/topics/edit.html.erb
<%=render 'form' %>

app/views/topics/index.html.erb
<strong> Total Topic publised </strong><span class="badge badge-warning"><%= Topic.all.count %></span>

<hr>
<div class="category_display">
  <strong>Sort by categories : </strong>
  <button type="button" class="btn-black">
    <%= link_to 'Actualité', topics_path(sort_actuality: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=0").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Loisir', topics_path(sort_losir: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=1").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Sport', topics_path(sort_sport: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=2").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Mode', topics_path(sort_mode: "true")%>
    <span class="badge badge-info"><%= Topic.where("category=3").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Tourisme', topics_path(sort_tourism: "true")%>
    <span class="badge badge-info"><%= Topic.where("category=4").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Politique', topics_path(sort_politique: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=5").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Voyage', topics_path(sort_voyage: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=6").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Sexe', topics_path(sort_sexe: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=7").count%></span>
  </button>
  <button type="button" class="btn-black">
    <%= link_to 'Cuisine', topics_path(sort_cuisine: "true") %>
    <span class="badge badge-info"><%= Topic.where("category=8").count%></span>
  </button>
</div>
<hr>
<div class="">
  <% @topic.each do |topic| %>
    <div class="card">
      <div class="card-header">
        <p><strong>Subjet </strong> : <%=topic.title%> <br>
        <strong>Catégory</strong> : <%=topic.category%><br>
        Post by : <strong><%= topic.user.name%></strong> at: <strong><%= topic.created_at%></strong><br>

        comments :<span class="badge badge-info"><%=topic.comments.count%></span>
        Likes : <span class="badge badge-danger"><%=topic.favorites.count%></span>
      </p>
      </div>
      <div class="card-body">
        <p><%=topic.content%></p>
     <%=link_to "comment",topic_path(topic.id),class:"btn btn-outline-info my-2 my-sm-0"%>
     <%if current_user && current_user== topic.user%>
      <%=link_to "Edit", edit_topic_path(topic.id),class:"badge badge-info" %>
      <%=link_to "Destroy",topic_path(topic.id),method: :delete, data: { confirm: 'Are you sure?'},class:"badge badge-light" %>
     <% end %>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/topics/new.html.erb
<%=render 'form' %>

app/views/topics/show.html.erb
 Post by : <strong><%= @topic.user.name%></strong></p>
<div class="card">
  <div class="card-header">
    <p>Topic : <strong><%= @topic.title %></strong><br>
       category: <strong><%= @topic.category %></strong> <br>
       comments :<span class="badge badge-info"><%=@topic.comments.count%></span>
       Likes : <span class="badge badge-danger"><%=@topic.favorites.count%></span>
  </div>
  <div class="card-body">
    <p> <%= @topic.content %></p>
    <% if user_signed_in? && current_user.id == @topic.user_id %>
     <%= link_to 'edit topic', edit_topic_path(@topic.id),class:"badge badge-info" %>
     <%= link_to 'Delete topic', topic_path(@topic.id), method: :delete, data: { confirm: 'Are you sure?'},class:"badge badge-danger"%>
    <% end %>

    <% if user_signed_in? %>
      <% unless @topic.user_id == current_user.id %>
        <% if current_user.favorites.pluck(:topic_id).include? @topic.id%>
          <%= link_to 'unlike', favorite_path(@favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'Like', favorites_path(topic_id: @topic.id), method: :post, class: 'btn btn-primary' %>
       <% end %>
    <% end %>
  <% end %>
  </div>
</div>
<hr>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
</div>
<br>
<div class="text-center">
  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
</div>