config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy, :show]
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
   }

  resources :users, only: %i[show index]

  root 'topics#index'
  resources :topics do
    resources :comments
  end

  resources :favorites, only: [:create, :destroy, :index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="page-top">
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
          <div class="container">
              <p class="navbar-brand js-scroll-trigger">DF_FORUM</p>
              <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  Menu
                  <i class="fas fa-bars"></i>
              </button>
              <% if user_signed_in? %>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item mx-0 mx-lg-1"><%= link_to 'Home', root_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %></li>
                      <li class="nav-item mx-0 mx-lg-1"><%= link_to 'All user', users_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %></li>
                      <li type="button" class="btn btn-outline-info my-2 my-sm-0 nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger nav-item mx-0 mx-lg-1" data-toggle="modal" data-target="#exampleModal"">SEARCH TOPIC BY NAME</li>
                      <li class="nav-item mx-0 mx-lg-1"><%= link_to "logout", destroy_user_session_path, method: :delete,class:" btn btn-outline-info my-2 my-sm-0 nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
                  </ul>
              </div>
            <% else %>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1"><%= link_to 'Home', root_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger' %></li>
                    <li class="nav-item mx-0 mx-lg-1"><%= link_to "Sign up", new_user_registration_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'%> </li>
                    <li class="nav-item mx-0 mx-lg-1"><%= link_to "Login", new_user_session_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'%></li>
                </ul>
            </div>
          <% end %>
          </div>
      </nav>
    <% if user_signed_in? %>
      <div class="nav2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <%= image_tag (current_user.avatar_thumbnail), class:"navbar-brand" , style:'height:50px;width:50px;border-radius:100px;'%>
            <small class="navbar-brand" href="#"><%= current_user.name %></small>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item ">
                  <%= link_to 'My profil', user_path(current_user.id), :class => 'nav-link' %>
                </li>
                <li class="nav-item ">
                  <%= link_to 'My topics', topics_path(sort_my_topic: "true"),:class => 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'My favorites topics',favorites_path,:class => 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Add topic', new_topic_path,:class => 'btn btn-outline-warning nav-link' %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    <% end %>

      <div class="container yield">
      <div class="flash">
         <% flash.each do |key, value|%>
           <%= content_tag(:div,value,class:"alert alert-#{key}")%>
          <%end%>
      </div>
      <%= yield %>
       <!-- searche by name Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <div class="form-inline">
                  <%= form_with(url: topics_path, method: :get, local: true) do |f|%>
                    <%= f.text_field :title , class:"form-control mr-sm-2", placeholder: "type the topic name here"%>
                    <%= f.submit'search', class:"btn btn-outline-success my-2 my-sm-0"%><br>
                    <span> <%= link_to "Clear search",root_path %></span>
                  <% end %>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>
 </body>
 <div class="">
 <%= render 'topics/footer' %>
 </div>
</html>